{"pytest_version": "5.2.0", "$report_type": "SessionStart"}
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "Caps/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "Common/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "PageObjects/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "PaggeLocators/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestDatas/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_prepare", "location": ["TestCases\\test_0_login.py", 11, "TestLogin.test_prepare"], "keywords": {"pytestmark": 1, "test_prepare": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestCases/__init__.py": 1, "TestLogin": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [["Captured log setup", "\u001b[32mINFO    \u001b[0m root:conftest.py:65 xxxxxxx\n\u001b[33mWARNING \u001b[0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '\u4f60\u7684\u4e3b\u673a\u4e2d\u7684\u8f6f\u4ef6\u4e2d\u6b62\u4e86\u4e00\u4e2a\u5df2\u5efa\u7acb\u7684\u8fde\u63a5\u3002', None, 10053, None))': /wd/hub/session/986ee887-aaf5-4cf1-9cca-90f61ab2acf9/appium/device/current_activity"]], "duration": 12.89608883857727, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_prepare", "location": ["TestCases\\test_0_login.py", 11, "TestLogin.test_prepare"], "keywords": {"pytestmark": 1, "test_prepare": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestCases/__init__.py": 1, "TestLogin": 1}, "outcome": "passed", "longrepr": null, "when": "call", "user_properties": [], "sections": [["Captured log setup", "\u001b[32mINFO    \u001b[0m root:conftest.py:65 xxxxxxx\n\u001b[33mWARNING \u001b[0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '\u4f60\u7684\u4e3b\u673a\u4e2d\u7684\u8f6f\u4ef6\u4e2d\u6b62\u4e86\u4e00\u4e2a\u5df2\u5efa\u7acb\u7684\u8fde\u63a5\u3002', None, 10053, None))': /wd/hub/session/986ee887-aaf5-4cf1-9cca-90f61ab2acf9/appium/device/current_activity"], ["Captured log call", "\u001b[32mINFO    \u001b[0m root:basepage.py:38 \u5143\u7d20('id', 'com.xxzb.fenwoo:id/btn_login')\u67e5\u627e\u6210\u529f\uff0c\u8017\u65f60.546370267868042s\n\u001b[32mINFO    \u001b[0m root:test_0_login.py:17 app\u5df2\u767b\u5f55,\u6267\u884c\u6570\u636e\u6e05\u7a7a\u64cd\u4f5c!"]], "duration": 0.5473461151123047, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_prepare", "location": ["TestCases\\test_0_login.py", 11, "TestLogin.test_prepare"], "keywords": {"pytestmark": 1, "test_prepare": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestCases/__init__.py": 1, "TestLogin": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [["Captured log setup", "\u001b[32mINFO    \u001b[0m root:conftest.py:65 xxxxxxx\n\u001b[33mWARNING \u001b[0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '\u4f60\u7684\u4e3b\u673a\u4e2d\u7684\u8f6f\u4ef6\u4e2d\u6b62\u4e86\u4e00\u4e2a\u5df2\u5efa\u7acb\u7684\u8fde\u63a5\u3002', None, 10053, None))': /wd/hub/session/986ee887-aaf5-4cf1-9cca-90f61ab2acf9/appium/device/current_activity"], ["Captured log call", "\u001b[32mINFO    \u001b[0m root:basepage.py:38 \u5143\u7d20('id', 'com.xxzb.fenwoo:id/btn_login')\u67e5\u627e\u6210\u529f\uff0c\u8017\u65f60.546370267868042s\n\u001b[32mINFO    \u001b[0m root:test_0_login.py:17 app\u5df2\u767b\u5f55,\u6267\u884c\u6570\u636e\u6e05\u7a7a\u64cd\u4f5c!"]], "duration": 0.7271194458007812, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_login_success", "location": ["TestCases\\test_0_login.py", 22, "TestLogin.test_login_success"], "keywords": {"pytestmark": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestLogin": 1, "TestCases/__init__.py": 1, "test_login_success": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 45.450828552246094, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_login_success", "location": ["TestCases\\test_0_login.py", 22, "TestLogin.test_login_success"], "keywords": {"pytestmark": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestLogin": 1, "TestCases/__init__.py": 1, "test_login_success": 1}, "outcome": "passed", "longrepr": null, "when": "call", "user_properties": [], "sections": [["Captured log call", "\u001b[32mINFO    \u001b[0m root:test_0_login.py:25 \u6210\u529f\u767b\u5f55\n\u001b[32mINFO    \u001b[0m root:bottom_widget.py:15 \u5207\u6362\u5230\u9875\u9762\u6211\n\u001b[32mINFO    \u001b[0m root:basepage.py:38 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u67e5\u627e\u6210\u529f\uff0c\u8017\u65f60.5664052963256836s\n\u001b[32mINFO    \u001b[0m root:basepage.py:47 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u67e5\u627e\u6210\u529f\uff01\n\u001b[32mINFO    \u001b[0m root:basepage.py:80 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u6210\u529f\u70b9\u51fb!"]], "duration": 1.4088242053985596, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_login_success", "location": ["TestCases\\test_0_login.py", 22, "TestLogin.test_login_success"], "keywords": {"pytestmark": 1, "test_0_login.py": 1, "test": 1, "AppFramework": 1, "usefixtures": 1, "()": 1, "TestLogin": 1, "TestCases/__init__.py": 1, "test_login_success": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [["Captured log call", "\u001b[32mINFO    \u001b[0m root:test_0_login.py:25 \u6210\u529f\u767b\u5f55\n\u001b[32mINFO    \u001b[0m root:bottom_widget.py:15 \u5207\u6362\u5230\u9875\u9762\u6211\n\u001b[32mINFO    \u001b[0m root:basepage.py:38 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u67e5\u627e\u6210\u529f\uff0c\u8017\u65f60.5664052963256836s\n\u001b[32mINFO    \u001b[0m root:basepage.py:47 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u67e5\u627e\u6210\u529f\uff01\n\u001b[32mINFO    \u001b[0m root:basepage.py:80 \u5143\u7d20('-android uiautomator', 'new UiSelector().text(\"\u6211\")')\u6210\u529f\u70b9\u51fb!"]], "duration": 0.9603841304779053, "_report_type": "TestReport"}
{"exitstatus": 0, "$report_type": "SessionFinish"}
