{"pytest_version": "5.2.0", "$report_type": "SessionStart"}
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "Caps/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "Common/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "PageObjects/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "PaggeLocators/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestDatas/__init__.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "_report_type": "CollectReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_prepare", "location": ["TestCases\\test_0_login.py", 11, "TestLogin.test_prepare"], "keywords": {"test_0_login.py": 1, "TestLogin": 1, "usefixtures": 1, "pytestmark": 1, "AppFramework": 1, "test_prepare": 1, "()": 1, "TestCases/__init__.py": 1, "test": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "D:\\python\\mystudy\\AppFramework\\TestCases\\conftest.py", "lineno": 39, "message": "TypeError: 'str' object is not callable"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture()", "    def init_reset():", "        driver = base_driver(automationName=None,noReset=True)", ">       swipe_welcome(driver)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 70, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def swipe_welcome(driver):", ">       activity = driver.current_activity()", "E       TypeError: 'str' object is not callable"], "reprfuncargs": {"args": [["driver", "<appium.webdriver.webdriver.WebDriver (session=\"3dd47b52-b107-405c-be6d-3785a8058657\")>"]]}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 39, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture()", "    def init_reset():", "        driver = base_driver(automationName=None,noReset=True)", ">       swipe_welcome(driver)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 70, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def swipe_welcome(driver):", ">       activity = driver.current_activity()", "E       TypeError: 'str' object is not callable"], "reprfuncargs": {"args": [["driver", "<appium.webdriver.webdriver.WebDriver (session=\"3dd47b52-b107-405c-be6d-3785a8058657\")>"]]}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 39, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "D:\\python\\mystudy\\AppFramework\\TestCases\\conftest.py", "lineno": 39, "message": "TypeError: 'str' object is not callable"}, null]]}, "when": "setup", "user_properties": [], "sections": [["Captured log setup", "\u001b[32mINFO    \u001b[0m root:conftest.py:61 xxxxxxx"]], "duration": 24.118877410888672, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_prepare", "location": ["TestCases\\test_0_login.py", 11, "TestLogin.test_prepare"], "keywords": {"test_0_login.py": 1, "TestLogin": 1, "usefixtures": 1, "pytestmark": 1, "AppFramework": 1, "test_prepare": 1, "()": 1, "TestCases/__init__.py": 1, "test": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [["Captured log setup", "\u001b[32mINFO    \u001b[0m root:conftest.py:61 xxxxxxx"]], "duration": 0.0009756088256835938, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_login_success", "location": ["TestCases\\test_0_login.py", 22, "TestLogin.test_login_success"], "keywords": {"test_login_success": 1, "test_0_login.py": 1, "TestLogin": 1, "usefixtures": 1, "pytestmark": 1, "AppFramework": 1, "()": 1, "TestCases/__init__.py": 1, "test": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "D:\\python\\mystudy\\AppFramework\\TestCases\\conftest.py", "lineno": 39, "message": "TypeError: 'str' object is not callable"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture()", "    def init_keep():", "        driver = base_driver(automationName=None,noReset=False)", ">       swipe_welcome(driver)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 78, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def swipe_welcome(driver):", ">       activity = driver.current_activity()", "E       TypeError: 'str' object is not callable"], "reprfuncargs": {"args": [["driver", "<appium.webdriver.webdriver.WebDriver (session=\"12657a43-74c7-488d-8cb1-36fb8a23c04c\")>"]]}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 39, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture()", "    def init_keep():", "        driver = base_driver(automationName=None,noReset=False)", ">       swipe_welcome(driver)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 78, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def swipe_welcome(driver):", ">       activity = driver.current_activity()", "E       TypeError: 'str' object is not callable"], "reprfuncargs": {"args": [["driver", "<appium.webdriver.webdriver.WebDriver (session=\"12657a43-74c7-488d-8cb1-36fb8a23c04c\")>"]]}, "reprlocals": null, "reprfileloc": {"path": "TestCases\\conftest.py", "lineno": 39, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "D:\\python\\mystudy\\AppFramework\\TestCases\\conftest.py", "lineno": 39, "message": "TypeError: 'str' object is not callable"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 9.731790781021118, "_report_type": "TestReport"}
{"nodeid": "TestCases/test_0_login.py::TestLogin::test_login_success", "location": ["TestCases\\test_0_login.py", 22, "TestLogin.test_login_success"], "keywords": {"test_login_success": 1, "test_0_login.py": 1, "TestLogin": 1, "usefixtures": 1, "pytestmark": 1, "AppFramework": 1, "()": 1, "TestCases/__init__.py": 1, "test": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.0009768009185791016, "_report_type": "TestReport"}
{"exitstatus": 1, "$report_type": "SessionFinish"}
